--INSERT TIPO ENTIDADE--
INSERT INTO SIGA.TB_TIPO_ENTIDADE(CD_TIPO_ENTIDADE, CD_NIVEL_HIERARQUICO, NM_TIPO_ENTIDADE,  TP_ENTIDADE_NIVEL_SUPERIOR, CD_TP_ENTIDADE_NIVEL_SUPERIOR) VALUES (1, 1, 'Confederação', '' , 0);
INSERT INTO SIGA.TB_TIPO_ENTIDADE(CD_TIPO_ENTIDADE, CD_NIVEL_HIERARQUICO, NM_TIPO_ENTIDADE,  TP_ENTIDADE_NIVEL_SUPERIOR, CD_TP_ENTIDADE_NIVEL_SUPERIOR) VALUES (2, 2, 'Federação',  'Confederação', 1);
INSERT INTO SIGA.TB_TIPO_ENTIDADE(CD_TIPO_ENTIDADE, CD_NIVEL_HIERARQUICO, NM_TIPO_ENTIDADE,  TP_ENTIDADE_NIVEL_SUPERIOR, CD_TP_ENTIDADE_NIVEL_SUPERIOR) VALUES (3, 3, 'Sindicato',  'Federação' , 2);
INSERT INTO SIGA.TB_TIPO_ENTIDADE(CD_TIPO_ENTIDADE, CD_NIVEL_HIERARQUICO, NM_TIPO_ENTIDADE,  TP_ENTIDADE_NIVEL_SUPERIOR, CD_TP_ENTIDADE_NIVEL_SUPERIOR) VALUES (4, 2, 'Associação',  'Confederação' , 1);
INSERT INTO SIGA.TB_TIPO_ENTIDADE(CD_TIPO_ENTIDADE, CD_NIVEL_HIERARQUICO, NM_TIPO_ENTIDADE,  TP_ENTIDADE_NIVEL_SUPERIOR, CD_TP_ENTIDADE_NIVEL_SUPERIOR) VALUES (5, 3, 'Centro de Industrias',  'Federação' , 2);

--INSERT PERFIL--
INSERT INTO SIGA.TB_PERFIL (CD_PERFIL,DS_MOTIVO_EXCLUSAO,NM_PERFIL,NR_SITUACAO_PERFIL,NR_SITUACAO_REGISTRO,CD_LOG_REGISTRO,CD_TIPO_ENTIDADE) values (1,null,'ACARC','1',null,null,1);

--INSERT SUBMENUS--

INSERT INTO SIGA.TB_SUBMENU (CD_SUBMENU, DS_ICON, DS_ID, DS_LABEL, DS_SIGLA, NR_SEQUENCIA) VALUES (1, 'icon-contacts',      'cadastros',         'Cadastros',             'CAD', 2);
INSERT INTO SIGA.TB_SUBMENU (CD_SUBMENU, DS_ICON, DS_ID, DS_LABEL, DS_SIGLA, NR_SEQUENCIA) VALUES (2, 'icon-cog-alt',       'infraestrutura',    'Infraestrutura',        'INF', 1);
INSERT INTO SIGA.TB_SUBMENU (CD_SUBMENU, DS_ICON, DS_ID, DS_LABEL, DS_SIGLA, NR_SEQUENCIA) VALUES (3, 'icon-briefcase-1',   'contabil',          'Contábil',              'COT', 8);
INSERT INTO SIGA.TB_SUBMENU (CD_SUBMENU, DS_ICON, DS_ID, DS_LABEL, DS_SIGLA, NR_SEQUENCIA) VALUES (4, 'icon-users-outline', 'crm',               'CRM',                   'CRM', 7);
INSERT INTO SIGA.TB_SUBMENU (CD_SUBMENU, DS_ICON, DS_ID, DS_LABEL, DS_SIGLA, NR_SEQUENCIA) VALUES (5, 'icon-sitemap',       'enquadramentoSind', 'Enquadramento Sindical','ENQ', 3);
INSERT INTO SIGA.TB_SUBMENU (CD_SUBMENU, DS_ICON, DS_ID, DS_LABEL, DS_SIGLA, NR_SEQUENCIA) VALUES (6, 'icon-calculator',    'cobrança',          'Cobrança',              'COB', 4);
INSERT INTO SIGA.TB_SUBMENU (CD_SUBMENU, DS_ICON, DS_ID, DS_LABEL, DS_SIGLA, NR_SEQUENCIA) VALUES (7, 'icon-list-alt',      'relatorios',        'Relatórios',            'REL', 6);
INSERT INTO SIGA.TB_SUBMENU (CD_SUBMENU, DS_ICON, DS_ID, DS_LABEL, DS_SIGLA, NR_SEQUENCIA) VALUES (8, 'icon-calendar-2',    'negociacao',        'Negociação',            'NEG', 5);
INSERT INTO SIGA.TB_SUBMENU (CD_SUBMENU, DS_ICON, DS_ID, DS_LABEL, DS_SIGLA, NR_SEQUENCIA) VALUES (9, 'icon-fa-users',       'relacionamento',    'Relacionamento',       'REC', 9);



--INSERT ACAO--
INSERT INTO SIGA.TB_ACAO (CD_ACAO, DS_ACAO, TP_ACAO) VALUES (1, 'Consultar', 'C');
INSERT INTO SIGA.TB_ACAO (CD_ACAO, DS_ACAO, TP_ACAO) VALUES (2, 'Incluir',   'I');
INSERT INTO SIGA.TB_ACAO (CD_ACAO, DS_ACAO, TP_ACAO) VALUES (3, 'Alterar',   'A');
INSERT INTO SIGA.TB_ACAO (CD_ACAO, DS_ACAO, TP_ACAO) VALUES (4, 'Excluir',   'E');

-------------------------------------------------------------------INSERT MENU-----------------------------------------------------------------

--INSERT CADASTRO-----
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(1, '#{manterEntidadeController.carregarConsultarEntidade}', null, null, 'manterEntidade', 'Entidade', 'Entidade',1, 1);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(2, '#{manterEmpresaController.carregarConsultarEmpresa}', null, null, 'manterEmpresa', 'Empresa', 'Empresa',1, 2);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(3, '#{manterPessoaFisicaController.carregarConsultarPessoaFisica}', null, null, 'manterPessoa', 'Pessoa Física', 'Pessoa Física',1, 3);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(4, '#{manterCnoController.carregarConsultarCno}', null, null, 'manterCno', 'CNO', 'CNO',1, 4);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(5, '#{manterCnaeController.carregarConsultarCnae}', null, null, 'manterCnae', 'CNAE', 'CNAE',1, 5);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(6, '#{manterPendenciaCadastralController.carregarConsultarPendenciaCadastral}', null, null, 'manterPendenciaCad', 'Pendência Cadastral', 'Pendência Cadastral',1, 6);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(7,'#{manterGrupoEconomicoController.carregarConsultarGrupoEconomico}', null, null, 'manterGrupoEco', 'Grupo Econômico', 'Grupo Econômico',1, 7);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(8, '#{manterGrupoEmpresarialController.carregarConsultarGrupoEmpresarial}', null, null, 'manterGrupoEmp', 'Grupo Empresarial', 'Grupo Empresarial',1, 8);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(9, '#{manterRegiaoController.carregarConsultarRegiao}', null, null, 'manterRegiao', 'Região', 'Região',1, 9);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(10, '#{manterLotacaoController.carregarConsultarLotacao}', null, null, 'manterLotacao', 'Lotação', 'Lotação',1, 10);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(11, '#{manterInformativosController.carregarConsultarInformativos}', null, null, 'manterInformativos','Informativos', 'Informativos',1, 11);

--INSERT INFRAESTRUTURA--
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(21,'#{manterUsuarioController.carregarConsultarUsuario}', null, null, 'manterUsuario', 'Usuário', 'Usuário',2, 1);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(22,'#{manterPerfilController.carregarConsultarPerfil}', null, null, 'manterPerfil', 'Perfil', 'Perfil',2, 2);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(23,'#{importarCnaeController.carregarIncluirCnae}', null, null, 'importarCnae', 'Importar CNAE ', 'Importar CNAE',2, 3);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(24,'#{importarCepController.carregarIncluirCep}', null, null, 'importarCep', 'Importar CEP ', 'Importar CEP',2, 4);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(25,'#{manterLogRegistroController.carregarConsultarLogRegistro}', null, null, 'manterLog', 'Log', 'Log de Transações',2, 5);

--INSERT CONTABIL--


--INSERT CRM--

--INSERT ENQUADRAMENTO SINDICAL--
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(56, '#{manterVinculoPotencialContribuinteController.carregarConsultarPotencialContribuiente}', null, null, 'manterVinculoPotenciaisCon','Potenciais Contribuintes', 'Potenciais Contribuintes',5, 1);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(57, '#{manterAtualizarEstabelecimentosController.carregarConsultarAtualizarEstabelecimentos}', null, null, 'manterAtualizarEst','Atualização Cadastral', 'Atualização Cadastral',5, 2);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(58, '#{vincularEnquadramentoSindicalController.carregarVincularEnquadramentoSindical}', null, null, 'vincularEnqSind', 'Enquadramento Sindical', 'Enquadramento Sindical',5, 3);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(59, '#{vincularReenquadramentoSindicalController.carregarVincularReenquadramentoSindical}', null, null, 'vincularReenqEmp', 'Reenquadramento', 'Reenquadramento',5, 4);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(60, '#{vincularConflitoEnquadramentoSindicalController.carregarVincularConflitoEnquadramentoSindical}', null, null, 'vincularConEnqSind', 'Conflito de Representação', 'Conflito de Representação',5, 5);


--INSERT COBRANÇA--
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(70, '#{manterCobrancaController.carregarConsultarCobranca}', null, null, 'manterCobran', 'Tipo de Cobrança', 'Tipo de Cobrança',6, 1);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(71, '#{manterTipoBaseCalculoController.carregarConsultarTipoBaseCalculo}', null, null, 'manterTipoBaseCalculo', 'Tipo Base de Cálculo', 'Tipo Base de Cálculo',6, 2);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(72, '#{manterInformacaoBancariaController.carregarConsultarInformacaoBancaria}', null, null, 'manterInformacaoBancaria', 'Informações Bancárias', 'Informações Bancárias',6, 3);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(73, '#{manterTabelaCalculoController.carregarConsultarTabelaCalculo}', null, null, 'manterTabelaCalculo', 'Tabela de Cálculo', 'Tabela de Cálculo',6, 4);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(74, '#{manterBaseCalculoController.carregarConsultarBaseCalculo}', null, null, 'manterBaseCalc', 'Base de Cálculo', 'Base de Cálculo',6, 5);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(75, '#{manterCobrancaSemTabelaController.carregarConsultarCobrancaSemTabela}', null, null, 'manterCobrancaSemTab', 'Cobrança Sem Tabela', 'Cobrança Sem Tabela',6, 6);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(76,'#{gerarArquivoRemessaController.carregarGerarBoleto}', null, null, 'gerarArquivoRemessa', 'Gerar Arquivo Remessa', 'Gerar Arquivo Remessa',6, 7);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(77, '#{gerarBoletoController.carregarGerarBoleto}', null, null, 'gerarBoleto', 'Gerar Boletos', 'Gerar Boletos',6, 8);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(78, '#{manterCargaArquivoRetornoController.carregarArquivoRetorno}', null, null, 'arquivoRetorno', 'Arquivo Retorno', 'Arquivo Retorno',6, 9);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(79, '#{manterContaCorrenteController.carregarConsultarContaCorrente}', null, null, 'contaCorrente', 'Conta Corrente', 'Conta Corrente',6, 10);


--INSERT RELATORIOS--
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM,DS_COMMAND,DS_CONTAINERSTYLECLASS,DS_ICON,DS_ID,DS_TITLE,DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) values 
(88,'#{relatorioRelacaoEntidadesController.carregarRelatarioRelacaoEntidades}',null,null,'relatorioRelacaoEntidadesController','Relação de Entidades','Relação de Entidades', 7, 1);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM,DS_COMMAND,DS_CONTAINERSTYLECLASS,DS_ICON,DS_ID,DS_TITLE,DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) values 
(89,'#{relatorioEmpresaEntidadesController.carregarRelatarioEmpresaEntidades}',null,null,'relatorioEmpresaEntidadesController','Empresas por Entidade','Empresas por Entidade', 7, 2);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM,DS_COMMAND,DS_CONTAINERSTYLECLASS,DS_ICON,DS_ID,DS_TITLE,DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) values 
(90,'#{relatorioResumidoBoletosEmitidosController.carregarRelatarioResumidoBoletosEmitidos}',null,null,'relatorioResumidoBoletosEmitidosController','Boletos Emitidos - Sintético','Boletos Emitidos - Sintético', 7, 3);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM,DS_COMMAND,DS_CONTAINERSTYLECLASS,DS_ICON,DS_ID,DS_TITLE,DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) values 
(91,'#{relatorioDetalhadoBoletosEmitidosController.carregarRelatarioDetalhadoBoletosEmitidos}',null,null,'relatorioDetalhadoBoletosEmitidosController','Boletos Emitidos - Analítico','Boletos Emitidos - Analítico', 7, 4);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM,DS_COMMAND,DS_CONTAINERSTYLECLASS,DS_ICON,DS_ID,DS_TITLE,DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) values 
(92,'#{relatorioFinanceiroResumidoController.carregarRelatorioFinanceiroResumido}',null,null,'relatorioFinanceiroResumidoController','Financeiro - Sintético','Financeiro - Sintético', 7, 5);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM,DS_COMMAND,DS_CONTAINERSTYLECLASS,DS_ICON,DS_ID,DS_TITLE,DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) values 
(93,'#{relatorioFinanceiroDetalhadoController.carregarRelatotioFinanceiroDetalhado}',null,null,'relatorioFinanceiroDetalhadoController','Financeiro - Analítico','Financeiro - Analítico', 7, 6);
INSERT into TB_MENUITEM (CD_MENUITEM,DS_COMMAND,DS_CONTAINERSTYLECLASS,DS_ICON,DS_ID,DS_TITLE,DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) values 
(94,'#{relatorioPendenciaCadastralController.carregarRelatorioPendenciaCadastral}',null,null,'relatorioPendenciaCadastralController','Pendência Cadastral','Pendência Cadastral', 7, 7);
INSERT into TB_MENUITEM (CD_MENUITEM,DS_COMMAND,DS_CONTAINERSTYLECLASS,DS_ICON,DS_ID,DS_TITLE,DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) values 
(95,'#{relatorioBaseCalculoController.carregarRelatarioBaseCalculo}',null,null,'relatorioBaseCalculoController','Base de Cálculo','Base de Cálculo', 7, 8);
INSERT into TB_MENUITEM (CD_MENUITEM,DS_COMMAND,DS_CONTAINERSTYLECLASS,DS_ICON,DS_ID,DS_TITLE,DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) values 
(96,'#{relatorioInadimplenciaController.carregarRelatarioInadimplencia}',null,null,'relatorioInadimplenciaController','Inadimplência','Inadimplência', 7, 9);

--INSERT NEGOCIAÇÃO--
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(103, '#{manterProrrogacaoVencimentoController.carregarConsultarProrrogacaoVencimento}', null, null, 'manterProrrogacaoVencimento', 'Prorrogação de Vencimento', 'Prorrogação de Vencimento',8, 1);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(104, '#{manterParcelamentoDividaController.carregarConsultarParcelamentoDivida}', null, null, 'manterParcelamentoDivida', 'Parcelamento de Dívida', 'Parcelamento de Dívida',8, 2);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(105, '#{manterAntecipacaoDescontoController.carregarConsultarAntecipacaoDesconto}', null, null, 'manterAntecipacaoDesconto', 'Antecipação de Vencimentos', 'Antecipação de Vencimentos',8, 3);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(106, '#{manterBaixaManualController.carregarConsultarBaixaManual}', null, null, 'manterBaixaManual', 'Baixa Manual', 'Baixa Manual',8, 4);

--INSERT RELACIONAMENTO--
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(117, '#{manterProdutoServicoController.carregarConsultarProdutoServico}', null, null, 'manterProdutoServico', 'Produtos e Serviços', 'Produtos e Serviços',9, 1);
INSERT INTO SIGA.TB_MENUITEM (CD_MENUITEM, DS_COMMAND, DS_CONTAINERSTYLECLASS, DS_ICON, DS_ID, DS_TITLE, DS_VALUE, CD_SUBMENU, NR_SEQUENCIA) VALUES 
(118, '#{manterAtendimentoController.carregarConsultarAtendimento}', null, null, 'manterAtendimento', 'Atendimento', 'Atendimento',9, 2);

--INSERT PERFIL_MENU--
INSERT INTO SIGA.TB_PERFIL_MENU (CD_PERFILMENU,CD_MENUITEM,CD_PERFIL,CD_SUBMENU) values (1,21,1,2);
INSERT INTO SIGA.TB_PERFIL_MENU (CD_PERFILMENU,CD_MENUITEM,CD_PERFIL,CD_SUBMENU) values (2,22,1,2);



--INSERT PERFIL_MENU_ACAO--
INSERT INTO SIGA.TB_PERFILMENU_ACAO (CD_PERFILMENUACAO,CD_ACAO,CD_PERFILMENU) values (1,1,1);
INSERT INTO SIGA.TB_PERFILMENU_ACAO (CD_PERFILMENUACAO,CD_ACAO,CD_PERFILMENU) values (2,2,1);
INSERT INTO SIGA.TB_PERFILMENU_ACAO (CD_PERFILMENUACAO,CD_ACAO,CD_PERFILMENU) values (3,3,1);
INSERT INTO SIGA.TB_PERFILMENU_ACAO (CD_PERFILMENUACAO,CD_ACAO,CD_PERFILMENU) values (4,4,1);
INSERT INTO SIGA.TB_PERFILMENU_ACAO (CD_PERFILMENUACAO,CD_ACAO,CD_PERFILMENU) values (5,1,2);
INSERT INTO SIGA.TB_PERFILMENU_ACAO (CD_PERFILMENUACAO,CD_ACAO,CD_PERFILMENU) values (6,2,2);
INSERT INTO SIGA.TB_PERFILMENU_ACAO (CD_PERFILMENUACAO,CD_ACAO,CD_PERFILMENU) values (7,3,2);
INSERT INTO SIGA.TB_PERFILMENU_ACAO (CD_PERFILMENUACAO,CD_ACAO,CD_PERFILMENU) values (8,4,2);

--INSERT LOCALIZA��O--
INSERT INTO SIGA.TB_LOCALIZACAO (CD_LOCALIZACAO,DS_BAIRRO,DS_CEP,DS_COMPLEMENTO,DS_LOGRADOURO,DS_NOME_FILIAL,DS_REGIAO_SINDICAL,NR_NUMERO,TP_LOCALIZACAO,CD_LOCALIDADE) values (1,'Asa Norte','70.040-903','ANDAR','SBN Quadra 1 Bloco C Edifício Roberto Simonsen',null,null,'17',null,1778);

--INSERT ENTIDADE--
INSERT INTO SIGA.TB_ENTIDADE (CD_ENTIDADE,CD_ABRANG_TERRITORIAL,CD_CENTRAL_SINDICAL,CD_CLASSE,CD_MOD_REPRESENTACAO,DS_CEDENTE,DS_CNPJ,DS_MOTIVO_EXCLUSAO,DS_NOME_PRESIDENTE,DS_SIGLA,DS_SITUACAO_CNES,DT_FIM_MANDATO,DT_INICIO_MANDATO,IC_ATUALIZAR_LOCALIDE,IC_ATUALIZAR_PRESIDENTE,NM_ENTIDADE,NM_LOGOMARCA,NR_ENTIDADE,NR_SITUACAO_ENTIDADE,NR_SITUACAO_REGISTRO,CD_ENTIDADE_VINCULADA,CD_LOG_REGISTRO,CD_TIPO_ENTIDADE) values (1,1,null,1,1,'000.001.000.00000-9','33.665.126/0001-34',null,'ROBSON BRAGA DE ANDRADE','CNI','Ativo',to_date('28/10/18','DD/MM/RR'),to_date('28/10/14','DD/MM/RR'),1,1,'CONFEDERAÇÂO NACIONAL DA INDÚSTRIA',null,null,1,null,1,null,1);
INSERT INTO SIGA.TB_ENTIDADE_LOCALIZACAO (CD_ENTIDADE_LOCALIZACAO,IC_MATRIZ,CD_ENTIDADE,CD_LOCALIZACAO) values (1,1,1,1);
INSERT INTO SIGA.TB_ENTIDADE_LOCALIDADE (CD_ENTIDADE_LOCALIDADE,CD_ENTIDADE,CD_LOCALIDADE) values (1,1,1778);
INSERT INTO SIGA.TB_ENTIDADE_UF (CD_ENTIDADE_UF,CD_ENTIDADE,CD_UF) values (1,1,7);

--INSERT LOTA��O--
INSERT INTO SIGA.TB_LOTACAO (CD_LOTACAO, NM_LOTACAO, ST_LOTACAO) VALUES (1, 'CNI-ACARC', 'Ativo');

--INSERT USUARIO--
INSERT INTO SIGA.TB_USUARIO (CD_USUARIO,DS_CPF,DS_EMAIL,DS_MOTIVO_EXCLUSAO,DS_SENHA,DS_TELEFONE,DT_CADASTRAMENTO,NM_USUARIO,NR_SITUACAO_REGISTRO,NR_SITUACAO_USUARIO,NR_USUARIO,TP_USUARIO,CD_LOTACAO,NR_PERFIL,CD_TIPO_ENTIDADE) values (1,'646.403.531-20','snegrao@cni.org.br',null,'123456','6133179206',to_date('03/11/05','DD/MM/RR'),'ACARC',null,1,1,1,1,1,1);

--INSERT USUARIO_ENTIDADE--
INSERT INTO SIGA.TB_USUARIO_ENTIDADE (CD_USUARIOENTIDADE,CD_ENTIDADE,CD_USUARIO) values (1,1,1);

--INSERT USUARIO_UF--
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (1,1,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (2,2,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (3,3,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (4,4,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (5,5,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (6,6,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (7,7,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (8,8,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (9,9,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (10,10,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (11,11,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (12,12,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (13,13,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (14,14,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (15,15,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (16,16,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (17,17,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (18,18,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (19,19,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (20,20,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (21,21,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (22,22,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (23,23,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (24,24,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (25,25,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (26,26,1);
INSERT INTO SIGA.TB_USUARIO_UF (CD_USUARIOUF,CD_UF,CD_USUARIO) values (27,27,1);

--INSERT FUNCIONALIDADE--
INSERT INTO SIGA.TB_FUNCIONALIDADE(CD_FUNCIONALIDADE, NM_FUNCIONALIDADE) VALUES (1, 'Cadastros');
INSERT INTO SIGA.TB_FUNCIONALIDADE(CD_FUNCIONALIDADE, NM_FUNCIONALIDADE) VALUES (2, 'Infraestrutura');
INSERT INTO SIGA.TB_FUNCIONALIDADE(CD_FUNCIONALIDADE, NM_FUNCIONALIDADE) VALUES (3, 'Contábil');
INSERT INTO SIGA.TB_FUNCIONALIDADE(CD_FUNCIONALIDADE, NM_FUNCIONALIDADE) VALUES (4, 'CRM');
INSERT INTO SIGA.TB_FUNCIONALIDADE(CD_FUNCIONALIDADE, NM_FUNCIONALIDADE) VALUES (5, 'Enquadramento Sindical');
INSERT INTO SIGA.TB_FUNCIONALIDADE(CD_FUNCIONALIDADE, NM_FUNCIONALIDADE) VALUES (6, 'Cobrança');
INSERT INTO SIGA.TB_FUNCIONALIDADE(CD_FUNCIONALIDADE, NM_FUNCIONALIDADE) VALUES (7, 'Relatórios');
INSERT INTO SIGA.TB_FUNCIONALIDADE(CD_FUNCIONALIDADE, NM_FUNCIONALIDADE) VALUES (8, 'Negociação');
INSERT INTO SIGA.TB_FUNCIONALIDADE(CD_FUNCIONALIDADE, NM_FUNCIONALIDADE) VALUES (9, 'Relacionamento');

--INSERT CENTRAL SINDICAL--
INSERT INTO SIGA.TB_CENTRAL_SINDICAL (CD_CENTRAL_SINDICAL, NM_CENTRAL_SINDICAL) VALUES (1, 'CUT - Central Única dos Trabalhadores');
INSERT INTO SIGA.TB_CENTRAL_SINDICAL (CD_CENTRAL_SINDICAL, NM_CENTRAL_SINDICAL) VALUES (2, 'FS - Força Sindical');
INSERT INTO SIGA.TB_CENTRAL_SINDICAL (CD_CENTRAL_SINDICAL, NM_CENTRAL_SINDICAL) VALUES (3, 'UGT - União Geral dos Trabalhadores');
INSERT INTO SIGA.TB_CENTRAL_SINDICAL (CD_CENTRAL_SINDICAL, NM_CENTRAL_SINDICAL) VALUES (4, 'CTB - Central dos Trabalhadores e Trabalhadoras do Brasil');
INSERT INTO SIGA.TB_CENTRAL_SINDICAL (CD_CENTRAL_SINDICAL, NM_CENTRAL_SINDICAL) VALUES (5, 'NCST - Nova Central Sindical de Trabalhadores');
INSERT INTO SIGA.TB_CENTRAL_SINDICAL (CD_CENTRAL_SINDICAL, NM_CENTRAL_SINDICAL) VALUES (6, 'CBDT - Central Brasileira Democrática dos Trabalhadores');
INSERT INTO SIGA.TB_CENTRAL_SINDICAL (CD_CENTRAL_SINDICAL, NM_CENTRAL_SINDICAL) VALUES (7, 'CONLUTAS');
INSERT INTO SIGA.TB_CENTRAL_SINDICAL (CD_CENTRAL_SINDICAL, NM_CENTRAL_SINDICAL) VALUES (8, 'UST - União Sindical dos Trabalhadores');
INSERT INTO SIGA.TB_CENTRAL_SINDICAL (CD_CENTRAL_SINDICAL, NM_CENTRAL_SINDICAL) VALUES (9, 'CSB - Central dos Sindicatos Brasileiros');
INSERT INTO SIGA.TB_CENTRAL_SINDICAL (CD_CENTRAL_SINDICAL, NM_CENTRAL_SINDICAL) VALUES (10, 'Central Unificada dos Profissionais Servidores Públicos do Brasil');
INSERT INTO SIGA.TB_CENTRAL_SINDICAL (CD_CENTRAL_SINDICAL, NM_CENTRAL_SINDICAL) VALUES (11, 'INTERSINDICAL');
INSERT INTO SIGA.TB_CENTRAL_SINDICAL (CD_CENTRAL_SINDICAL, NM_CENTRAL_SINDICAL) VALUES (12, 'PÚBLICA');
INSERT INTO SIGA.TB_CENTRAL_SINDICAL (CD_CENTRAL_SINDICAL, NM_CENTRAL_SINDICAL) VALUES (13, 'CGTB - Central Geral dos Trabalhadores do Brasil');
INSERT INTO SIGA.TB_CENTRAL_SINDICAL (CD_CENTRAL_SINDICAL, NM_CENTRAL_SINDICAL) VALUES (14, 'CSB - Central dos Sindicatos Brasileiros');
INSERT INTO SIGA.TB_CENTRAL_SINDICAL (CD_CENTRAL_SINDICAL, NM_CENTRAL_SINDICAL) VALUES (15, 'INTERSINDICAL');

--INSERT BANCOS--
Insert INTO SIGA.TB_BANCO (CD_BANCO,NM_RAZAO_SOCIAL,NR_SITUACAO) values ('1','BANCO DO BRASIL','1');
Insert INTO SIGA.TB_BANCO (CD_BANCO,NM_RAZAO_SOCIAL,NR_SITUACAO) values ('41','BANRISUL','1');
Insert INTO SIGA.TB_BANCO (CD_BANCO,NM_RAZAO_SOCIAL,NR_SITUACAO) values ('104','CAIXA ECONOMICA FEDERAL','1');
Insert INTO SIGA.TB_BANCO (CD_BANCO,NM_RAZAO_SOCIAL,NR_SITUACAO) values ('237','BRADESCO','1');
Insert INTO SIGA.TB_BANCO (CD_BANCO,NM_RAZAO_SOCIAL,NR_SITUACAO) values ('341','ITAU','1');
Insert INTO SIGA.TB_BANCO (CD_BANCO,NM_RAZAO_SOCIAL,NR_SITUACAO) values ('748','SICREDI','1');
Insert INTO SIGA.TB_BANCO (CD_BANCO,NM_RAZAO_SOCIAL,NR_SITUACAO) values ('756','SICOOB','1');


--Insert INTO SIGA.TB_ENTIDADE_CNES (ID_ENTIDADE,CNPJ,CODIGO_SINDICAL,DATA_ALTERACAO,DENOMINACAO,EMAIL,GRAU_ENTIDADE,RAZAO_SOCIAL,SITE,SITUACAO) values ('1','22.496.945/0001-89','000.000.000.00000-0',to_date('22/02/16','DD/MM/RR'),'Comit� Brasileiro da C�mara de Com�rcio Internacional - ICC BRASIL, ICC BRASIL',null ,'1','Comit� Brasileiro da C�mara de Com�rcio Internacional - ICC BRASIL',null,'1');
--Insert INTO SIGA.TB_CONTATO_CNES (ID_CONTATO,DDD,RAMAL,TELEFONE,FK_ID_ENTIDADE) values ('1','95',null,'36254493','1');
--Insert INTO SIGA.TB_CONTATO_CNES (ID_CONTATO,DDD,RAMAL,TELEFONE,FK_ID_ENTIDADE) values ('2','95',null,'99597199','1');
--Insert INTO SIGA.TB_DIRETORIA_CNES (ID_DIRETORIA,CNPJ,DATA_FIM_MANDATO,DATA_INICIO_MANDATO,FK_ID_ENTIDADE) values ('1','22.496.945/0001-89',to_date('15/07/17','DD/MM/RR'),to_date('15/07/14','DD/MM/RR'),'1');
--Insert INTO SIGA.TB_DIRIGENTE_CNES (ID_DIRIGENTE,CARGO,CNPJ,CPF,CS,NOME_DIRIGENTE_SINDICAL,RF,FK_ID_DIRETORIA) values ('1','Presidente','22.496.945/0001-89','775.419.523-20','1','DANIEL FEFFER','1','1');
--Insert INTO SIGA.TB_DIRIGENTE_CNES (ID_DIRIGENTE,CARGO,CNPJ,CPF,CS,NOME_DIRIGENTE_SINDICAL,RF,FK_ID_DIRETORIA) values ('2','Administrador','22.496.945/0001-89','383.521.842-53','1','JOSE AUGUSTO COELHO FERNANDES','2','1');
--Insert INTO SIGA.TB_LOCALIZACAO_CNES (ID_LOCALIZACAO,BAIRRO,CEP,COMPLEMENTO,LOCALIDADE,LOGRADOURO,NUMERO,SIGLA_UF,FK_ID_ENTIDADE) values ('1','Cidade Mon��es','00.000-000','Rua Surubim, 504 - Andar 2 - Conjunto 22','Sao Paulo/SP','Rua Surubim','504','SP','1');
--Insert INTO SIGA.TB_REPRESENTACAO_CNES (ID_REPRESENTACAO,ABRANGENCIA,AREA_GEOECONOMICA,BASE_TERRITORIAL,CATEGORIA,CLASSE,GRUPO,FK_ID_ENTIDADE) values ('1','1','1','Nacional','Comit� Brasileiro da C�mara de Com�rcio Internacional','7','2','1');

